---
title: "CS106B: Programming Abstractions"
subtitle: "Section 3: Recursion and Intro to Backtracking"
author: "Olivia Beyer Bruvik"
date: "Fall 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Section 3: Recursion and Intro to Backtracking {.tabset}

## Material
<https://web.stanford.edu/class/cs106b/section/section3/>

- recursive backtracking

## Q3: Random Shuffling (shuffle.cpp) {.tabset}
Topics: Recursion, strings, recursion tracing

### Problem
How might the computer shuffle a deck of cards? This problem is a bit more complex than it might seem, and while it's easy to come up with algorithms that randomize the order of the cards, only a few algorithms will do so in a way that ends up generating a uniformly-random reordering of the cards.<br>

One simple algorithm for shuffling a deck of cards is based on the following idea:

1. Choose a random card from the deck and remove it.
2. Shuffle the rest of the deck.
3. Place the randomly-chosen card on top of the deck. Assuming that we choose the card that we put on top uniformly at random from the deck, this ends up producing a random shuffle of the deck.

Write a function: `string randomShuffle(string input)` that accepts as input a string, then returns a random permutation of the elements of the string using the above algorithm. Your algorithm should be recursive and not use any loops (for, while, etc.). <br>

The header file "random.h" includes a function `int randomInteger(int low, int high);` that takes as input a pair of integers low and high, then returns an integer greater than or equal to low and less than or equal to high. Feel free to use that here.

### Solution
```{Rcpp, eval = FALSE}
string randomShuffle(string input){
    if (input.empty()) {
        return "";
    }
    int i = randomInteger(0, input.length() - 1);
    return input[i] + randomShuffle(input.substr(0, i) + input.substr(i + 1));
}

```

### Alternative (posted) solution
```{Rcpp, eval = FALSE}
void randomShuffle(string &input){
    if (input == "") return;
    int rand = randomInteger(0, input.length() - 1);
    char chosen = input[rand];
    input.erase(rand, 1);
    randomShuffle(input);
    input = chosen + input;
}
```

## Q4: Zig Zag (zigzag.cpp) {.tabset}
Topics: Recursion, printing output to console

### Problem
Write a recursive function named zigzag that returns a string of n characters as follows. The middle character (or middle two characters if n is even) is an asterisk (*). All characters before the asterisks are '<'. All characters after are '>'. Report an error if n is not positive.

`Call            Output`
`zigzag(1)       * `
`zigzag(4)       <**> `
`zigzag(9)       <<<<*>>>>`

### Solution
```{Rcpp, eval = FALSE}
string zigzag(int n){
    if (n < 1) error("negative inputs not allowed!");
    if (n == 1) {
        return "*";
    } else if (n == 2) {
        return "**";
    }
    return "<" + zigzag(n - 2) + ">";
}
```

### {Posted solution}
```{Rcpp, eval = FALSE}
string zigzag(int n) {
    if (n < 1) {
        error("The value of n was negative");
    } else if (n == 1) {
        return "*";
    } else if (n == 2) {
        return "**";
    } else {
        return "<" + zigzag(n-2) + ">";
    }
}
```


## Q5: Double Stack (double.cpp) {.tabset}
Topics: Recursion, Stacks

### Problem
Write a recursive function named doubleStack that takes a reference to a stack of ints and replaces each integer with two copies of that integer. For example, if s stores {1, 2, 3}, then doubleStack(s) changes it to {1, 1, 2, 2, 3, 3}.

### Solution
```{Rcpp, eval = FALSE}
void doubleStack(Stack<int> & s){
    if (s.isEmpty()) {
        return;
    } else {
        int n = s.pop();
        doubleStack(s);
        s.push(n);
        s.push(n);
    }
}
```

### Posted solution
```{Rcpp, eval = FALSE}
void doubleStack(Stack<int>& s) 
{ 
    if (!s.isEmpty()) {
        int n = s.pop();
        doubleStack(s); 
        s.push(n); 
        s.push(n);
    }
}
```

## Q6: String Subsequences (subsequence.cpp) {.tabset}
Topics: Recursion, verifying properties

### Problem
Write a recursive function named isSubsequence that takes two strings and returns true if the second string is a subsequence of the first string. A string is a subsequence of another if it contains the same letters in the same order, but not necessarily consecutively. You can assume both strings are already lower-cased.

`Call                                    Output`
`isSubsequence("computer", "core")       false `
`isSubsequence("computer", "cope")       true `
`isSubsequence("computer", "computer")   true`


### Solution
```{Rcpp, eval = FALSE}
bool isSubsequence(string big, string small) {
    if (small.empty()) return true;\
    char letter = small[0];
    int index = big.find(letter);
    if (index >= 0) {
        return isSubsequence(big.substr(index), small.substr(1));
    }
    return false;
}
```

### Posted solution
```{Rcpp, eval = FALSE}
bool isSubsequence(string big, string small) 
{ 
    if (small.empty()) {
        return true;
    } else if (big.empty()) {
        return false;
    } else {
        if (big[0] == small[0]) {
            return isSubsequence(big.substr(1), small.substr(1));
        } else {
            return isSubsequence(big.substr(1), small);
        } 
    }
}
```

## 7) Recursion and Time Complexity and Exponents, (Big-)Oh My
Topics: recursion, time complexity, big O, algorithm comparison

Below is a simple function that computes the value of m^n when n is a nonnegative integer:
```{Rcpp, eval = FALSE}
int raiseToPower(int m, int n) {
    int result = 1;
    for (int i = 0; i < n; i++) {
        result *= m;
    }
    return result;
}
```

1) What is the big-O complexity of the above function, written in terms of m and n? You can assume that it takes time O(1) to multiply two numbers. `O(n)`

2) If it takes 1 microsecond (μs) to compute raiseToPower(100, 100), approximately how long will it take to compute raiseToPower(200, 10000)? `100 microseconds`

Below is a recursive function that computes the value of m^n when n is a nonnegative integer:
```{Rcpp, eval = FALSE}
int raiseToPower(int m, int n) {
    if (n == 0) return 1;
    return m * raiseToPower(m, n - 1);
}
```

3) What is the big-O complexity of the above function, written in terms of m and n? You can assume that it takes time O(1) to multiply two numbers. `O(n)`

4) If it takes 1μs to compute raiseToPower(100, 100), approximately how long will it take to compute raiseToPower(200, 10000)? `100μs`

Here’s an alternative recursive function for computing m^n that uses a technique called exponentiation by squaring. The idea is to modify the recursive step as follows:

1. If n is an even number, then we can write n as n = 2k. Then m^n = m^(2k) = (m^k)^2.
2. If n is an odd number, then we can write n as n = 2k + 1. Then m^n = m^(2k+1) = m * m^(2k) = m * (m^k)^2.

Based on this observation, we can write this recursive function:
```{Rcpp, eval = FALSE}
int raiseToPower(int m, int n) {
    if (n == 0) {
        return 1;
    } else if (n % 2 == 0) {
        int halfPower = raiseToPower(m, n / 2);
        return halfPower * halfPower;
    } else {
        int halfPower = raiseToPower(m, n / 2);
        return m * halfPower * halfPower;
    }
}
```

5) What is the big-O complexity of the above function, written in terms of m and n? You can assume that it takes time O(1) to multiply two numbers. `O(log n)`

6) If it takes 1μs to compute raiseToPower(100, 100), approximately how long will it take to compute raiseToPower(200, 10000)? `2μs`

## 8) Win some, lose sum (sum.cpp) {.tabset}
Topics: recursive backtracking

### Problem
Write a recursive function named canMakeSum that takes a reference to a Vector<int> and an int target value and returns true if it is possible to have some selection of values from the Vector that sum to the target value. In particular, you should be implementing a function with the following declaration:

`bool canMakeSum(Vector<int>& values, int target)`

For example, let's say that we executed the following code:

`Vector<int> nums = {1,1,2,3,5};`
`canMakeSum(nums, 9)`

We should expect that the call to canMakeSum should return true. Given the values specified in nums, we can select 1, 3, and 5 such that 5 + 3 + 1 = 9. However, let's say that we executed the following code instead:

`Vector<int> nums = {1,4,5,6};`
`canMakeSum(nums, 8);`

We should expect that the call to canMakeSum in this case should return false, since there is no possible combination of values from the vector that sum up to the target value of 8.

### Solution
```{Rcpp, eval = FALSE}
bool canMakeSumHelper(Vector<int>& values, int target, int index) {
    if (index >= values.size()) {
        return target == 0;
    }

    return canMakeSumHelper(values, target - values[index], index + 1) ||
           canMakeSumHelper(values, target, index + 1);
}


bool canMakeSum(Vector<int>& values, int target) {
    return canMakeSumHelper(values, target, 0);
}
```

### Posted solution
```{Rcpp, eval = FALSE}
bool canMakeSumHelper(Vector<int>& v, int target, int cur, int index) {
	if (index >= v.size()) {
		return cur == target;
	}
	return canMakeSumHelper(v, target, cur + v[index], index + 1) ||
		   canMakeSumHelper(v, target, cur, index + 1);
}

bool canMakeSum(Vector<int>& v, int target) {
	return canMakeSumHelper(v, target, 0, 0);
}
```

## Q9: Weights {.tabset}
### Solution

```{Rcpp, eval = FALSE}
bool isMeasurableHelper(int target, Vector<int>& weights, int index) {
    if (index >= weights.size()) {
        return target == 0;
    }
    return isMeasurableHelper(target + weights[index], weights, index + 1) ||
           isMeasurableHelper(target - weights[index], weights, index + 1) ||
           isMeasurableHelper(target, weights, index + 1);
}

bool isMeasurable(int target, Vector<int>& weights) {
    return isMeasurableHelper(target, weights, 0);
}
```

### Posted solution
```{Rcpp, eval = FALSE}
bool isMeasurable(int target, Vector<int>& weights) {
	if (weights.isEmpty()) {
		return target == 0; // base case; no weights left to place
	} else {
		int last = weights[weights.size() - 1]; //using last index is fastest
		weights.remove(weights.size() - 1);

		// "choose and explore" all of the three possibilities
		bool result = isMeasurable(target + last, weights) ||
			   isMeasurable(target - last, weights) ||
			   isMeasurable(target, weights);
		// un-choose
		weights.add(last);
		return result;
 	}
}
```