---
title: "CS106B: Programming Abstractions"
subtitle: "Stanford University"
author: "Olivia Beyer Bruvik"
date: "Fall 2021"
output: html_document
---

```{r setup, include=FALSE}
options(knitr.duplicate.label='allow')
```

```{r child = "CS106B_L27.Rmd"}
```

```{r child = "CS106B_L26.Rmd"}
```

```{r child = "CS106B_L25.Rmd"}
```

```{r child = "CS106B_L24.Rmd"}
```

```{r child = "CS106B_L23.Rmd"}
```

```{r child = "CS106B_L22.Rmd"}
```

```{r child = "CS106B_L21.Rmd"}
```

```{r child = "CS106B_L20.Rmd"}
```

```{r child = "CS106B_L18.Rmd"}
```

```{r child = "CS106B_L17.Rmd"}
```

```{r child = "CS106B_L16.Rmd"}
```
```{r child = "CS106B_L15.Rmd"}
```


```{r child = "CS106B_L14.Rmd"}
```

```{r child = "CS106B_L13.Rmd"}
```

```{r child = "CS106B_L9.Rmd"}
```

```{r child = "CS106B_L8.Rmd"}
```

```{r child = "CS106B_L7.Rmd"}
```

```{r child = "CS106B_L6.Rmd"}
```

```{r child = "CS106B_L4.Rmd"}
```

```{r child = "CS106B_L3.Rmd"}
```

```{r child = "CS106B_L2.Rmd"}
```

```{r child = "CS106B_L1.Rmd"}
```


