---
title: "CS106B: Programming Abstractions"
subtitle: "Lecture 6: unordered DS"
author: "Olivia Beyer Bruvik"
date: "Fall 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Lecture 4 {.tabset}

## Topics

1. Abstract Data Types (ADT): 
    + language-independent models of common containers
    + encompass data's nature (ordered, paired) and accessibility (search, add/remove)
2. Performance:
    + optimize ADT use for efficiency
    + pass by reference
    + test with `Rcpp TIME_OPERATION(Vector.size(), function(Vector))`
  
## Vector ADT
- Similar to array/list
- Use Stanford library Vector, not C++ STL vector (NB! capitalization)
- Must be homogenous (same data type)
- Type goes in the <> after class name Vector

### Template syntax
```{Rcpp, eval = FALSE}
#include <Rcpp.h>
using namespace Rcpp;

#include "vector.h"                       // note quotes for Stanford version
Vector<string> lines;                     // note uppercase V here
Vector<double> measurementsData;
Vector<Vector<int>> allAssignmentScores;  // 2D vector

// Examples of using a vector
pset3Scores.add(98);
cout << pset3Scores[0] << endl;           // prints 98
cout << pset3Scores.size() << endl;       // prints 1
```

## Performance
### Vector performance warning
`use v.add()` to add elements at end of vector instead of insert/remove():

1. `v.insert(2, 42)`: shifts elements right to make room for the element
2. `v.remove(1)`: shifts element left to cover space left by removed element

### Testing performance
```{Rcpp, eval = FALSE}
/********** Test Cases ***********/
PROVIDED_TEST("Timing comparison")
{
  int size = 500000;
  TIME_OPERATION(size, runInsert(size));
  TIME_OPERATION(size, runAdd(size));
}
  
```

### Parameter passing
Always use pass-by-reference for containers like Vector and Grid for efficiency (no copy).

```{Rcpp, eval = FALSE}
void printFirst(Vector<int>& input) {
  cout << input[0] << endl;
}
```

## Grid container
ADT abstration similar to an array of arrays (matrix)

```{Rcpp, eval = FALSE}
#include <Rcpp.h>
#include "grid.h"
using namespace Rcpp;

Grid<int> chessboard;
Grid<int> image;
Grid<double> realMatrix;

void printMe(Grid<int>& grid, int row, int col) {
  for (int r = row - 1; r <= row + 1; r++) {
    for (int c = col - 1; c <= col + 1; c++) {
      if (grid.inBounds(r, c)) {
        cout << grid[r][c] << " ";
      }
    }
    cout << endl;
  }
}
```
